package com.poli.tracker_data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Nutriments(
    @Json(name = "acide-alpha-linolenique-omega-3")
    val acideAlphaLinoleniqueOmega3: Double,
    @Json(name = "acide-alpha-linolenique-omega-3_100g")
    val acideAlphaLinoleniqueOmega3100g: Double,
    @Json(name = "acide-alpha-linolenique-omega-3_label")
    val acideAlphaLinoleniqueOmega3Label: String,
    @Json(name = "acide-alpha-linolenique-omega-3_serving")
    val acideAlphaLinoleniqueOmega3Serving: Double,
    @Json(name = "acide-alpha-linolenique-omega-3_unit")
    val acideAlphaLinoleniqueOmega3Unit: String,
    @Json(name = "acide-alpha-linolenique-omega-3_value")
    val acideAlphaLinoleniqueOmega3Value: Double,
    @Json(name = "alcohol")
    val alcohol: Int,
    @Json(name = "alcohol_100g")
    val alcohol100g: Int,
    @Json(name = "alcohol_serving")
    val alcoholServing: Int,
    @Json(name = "alcohol_unit")
    val alcoholUnit: String,
    @Json(name = "alcohol_value")
    val alcoholValue: Int,
    @Json(name = "alpha-linolenic-acid")
    val alphaLinolenicAcid: Int,
    @Json(name = "alpha-linolenic-acid_100g")
    val alphaLinolenicAcid100g: Int,
    @Json(name = "alpha-linolenic-acid_serving")
    val alphaLinolenicAcidServing: Int,
    @Json(name = "alpha-linolenic-acid_unit")
    val alphaLinolenicAcidUnit: String,
    @Json(name = "alpha-linolenic-acid_value")
    val alphaLinolenicAcidValue: Int,
    @Json(name = "calcium")
    val calcium: Double,
    @Json(name = "calcium_100g")
    val calcium100g: Double,
    @Json(name = "calcium_label")
    val calciumLabel: String,
    @Json(name = "calcium_serving")
    val calciumServing: Double,
    @Json(name = "calcium_unit")
    val calciumUnit: String,
    @Json(name = "calcium_value")
    val calciumValue: Double,
    @Json(name = "carbohydrates")
    val carbohydrates: Double,
    @Json(name = "carbohydrates_100g")
    val carbohydrates100g: Double,
    @Json(name = "carbohydrates_prepared_unit")
    val carbohydratesPreparedUnit: String,
    @Json(name = "carbohydrates_serving")
    val carbohydratesServing: Double,
    @Json(name = "carbohydrates_unit")
    val carbohydratesUnit: String,
    @Json(name = "carbohydrates_value")
    val carbohydratesValue: Double,
    @Json(name = "carbon-footprint-from-known-ingredients_100g")
    val carbonFootprintFromKnownIngredients100g: Double,
    @Json(name = "carbon-footprint-from-known-ingredients_product")
    val carbonFootprintFromKnownIngredientsProduct: Double,
    @Json(name = "carbon-footprint-from-known-ingredients_serving")
    val carbonFootprintFromKnownIngredientsServing: Double,
    @Json(name = "cholesterol")
    val cholesterol: Int,
    @Json(name = "cholesterol_100g")
    val cholesterol100g: Int,
    @Json(name = "cholesterol_unit")
    val cholesterolUnit: String,
    @Json(name = "cholesterol_value")
    val cholesterolValue: Int,
    @Json(name = "cocoa")
    val cocoa: Double,
    @Json(name = "cocoa_100g")
    val cocoa100g: Double,
    @Json(name = "cocoa_label")
    val cocoaLabel: String,
    @Json(name = "cocoa_serving")
    val cocoaServing: Double,
    @Json(name = "cocoa_unit")
    val cocoaUnit: String,
    @Json(name = "cocoa_value")
    val cocoaValue: Double,
    @Json(name = "energy")
    val energy: Int,
    @Json(name = "energy_100g")
    val energy100g: Int,
    @Json(name = "energy-kcal")
    val energyKcal: Double,
    @Json(name = "energy-kcal_100g")
    val energyKcal100g: Double,
    @Json(name = "energy-kcal_prepared_unit")
    val energyKcalPreparedUnit: String,
    @Json(name = "energy-kcal_serving")
    val energyKcalServing: Double,
    @Json(name = "energy-kcal_unit")
    val energyKcalUnit: String,
    @Json(name = "energy-kcal_value")
    val energyKcalValue: Double,
    @Json(name = "energy-kj")
    val energyKj: Int,
    @Json(name = "energy-kj_100g")
    val energyKj100g: Int,
    @Json(name = "energy-kj_prepared_unit")
    val energyKjPreparedUnit: String,
    @Json(name = "energy-kj_serving")
    val energyKjServing: Double,
    @Json(name = "energy-kj_unit")
    val energyKjUnit: String,
    @Json(name = "energy-kj_value")
    val energyKjValue: Int,
    @Json(name = "energy_prepared_unit")
    val energyPreparedUnit: String,
    @Json(name = "energy_serving")
    val energyServing: Double,
    @Json(name = "energy_unit")
    val energyUnit: String,
    @Json(name = "energy_value")
    val energyValue: Double,
    @Json(name = "fat")
    val fat: Double,
    @Json(name = "fat_100g")
    val fat100g: Double,
    @Json(name = "fat_prepared_unit")
    val fatPreparedUnit: String,
    @Json(name = "fat_serving")
    val fatServing: Double,
    @Json(name = "fat_unit")
    val fatUnit: String,
    @Json(name = "fat_value")
    val fatValue: Double,
    @Json(name = "fiber")
    val fiber: Double,
    @Json(name = "fiber_100g")
    val fiber100g: Double,
    @Json(name = "fiber_prepared_unit")
    val fiberPreparedUnit: String,
    @Json(name = "fiber_serving")
    val fiberServing: Double,
    @Json(name = "fiber_unit")
    val fiberUnit: String,
    @Json(name = "fiber_value")
    val fiberValue: Double,
    @Json(name = "fruits-vegetables-nuts")
    val fruitsVegetablesNuts: Double,
    @Json(name = "fruits-vegetables-nuts_100g")
    val fruitsVegetablesNuts100g: Double,
    @Json(name = "fruits-vegetables-nuts-estimate")
    val fruitsVegetablesNutsEstimate: Int,
    @Json(name = "fruits-vegetables-nuts-estimate_100g")
    val fruitsVegetablesNutsEstimate100g: Int,
    @Json(name = "fruits-vegetables-nuts-estimate-from-ingredients_100g")
    val fruitsVegetablesNutsEstimateFromIngredients100g: Double,
    @Json(name = "fruits-vegetables-nuts-estimate-from-ingredients_serving")
    val fruitsVegetablesNutsEstimateFromIngredientsServing: Double,
    @Json(name = "fruits-vegetables-nuts-estimate_label")
    val fruitsVegetablesNutsEstimateLabel: String,
    @Json(name = "fruits-vegetables-nuts-estimate_serving")
    val fruitsVegetablesNutsEstimateServing: Int,
    @Json(name = "fruits-vegetables-nuts-estimate_unit")
    val fruitsVegetablesNutsEstimateUnit: String,
    @Json(name = "fruits-vegetables-nuts-estimate_value")
    val fruitsVegetablesNutsEstimateValue: Int,
    @Json(name = "fruits-vegetables-nuts_label")
    val fruitsVegetablesNutsLabel: String,
    @Json(name = "fruits-vegetables-nuts_serving")
    val fruitsVegetablesNutsServing: Double,
    @Json(name = "fruits-vegetables-nuts_unit")
    val fruitsVegetablesNutsUnit: String,
    @Json(name = "fruits-vegetables-nuts_value")
    val fruitsVegetablesNutsValue: Double,
    @Json(name = "iron")
    val iron: Double,
    @Json(name = "iron_100g")
    val iron100g: Double,
    @Json(name = "iron_label")
    val ironLabel: String,
    @Json(name = "iron_serving")
    val ironServing: Double,
    @Json(name = "iron_unit")
    val ironUnit: String,
    @Json(name = "iron_value")
    val ironValue: Double,
    @Json(name = "magnesium")
    val magnesium: Double,
    @Json(name = "magnesium_100g")
    val magnesium100g: Double,
    @Json(name = "magnesium_label")
    val magnesiumLabel: String,
    @Json(name = "magnesium_serving")
    val magnesiumServing: Double,
    @Json(name = "magnesium_unit")
    val magnesiumUnit: String,
    @Json(name = "magnesium_value")
    val magnesiumValue: Double,
    @Json(name = "monounsaturated-fat")
    val monounsaturatedFat: Double,
    @Json(name = "monounsaturated-fat_100g")
    val monounsaturatedFat100g: Double,
    @Json(name = "monounsaturated-fat_label")
    val monounsaturatedFatLabel: String,
    @Json(name = "monounsaturated-fat_serving")
    val monounsaturatedFatServing: Double,
    @Json(name = "monounsaturated-fat_unit")
    val monounsaturatedFatUnit: String,
    @Json(name = "monounsaturated-fat_value")
    val monounsaturatedFatValue: Double,
    @Json(name = "nova-group")
    val novaGroup: Int,
    @Json(name = "nova-group_100g")
    val novaGroup100g: Int,
    @Json(name = "nova-group_serving")
    val novaGroupServing: Int,
    @Json(name = "nutrition-score-fr")
    val nutritionScoreFr: Int,
    @Json(name = "nutrition-score-fr_100g")
    val nutritionScoreFr100g: Int,
    @Json(name = "pantothenic-acid")
    val pantothenicAcid: Double,
    @Json(name = "pantothenic-acid_100g")
    val pantothenicAcid100g: Double,
    @Json(name = "pantothenic-acid_label")
    val pantothenicAcidLabel: String,
    @Json(name = "pantothenic-acid_serving")
    val pantothenicAcidServing: Double,
    @Json(name = "pantothenic-acid_unit")
    val pantothenicAcidUnit: String,
    @Json(name = "pantothenic-acid_value")
    val pantothenicAcidValue: Double,
    @Json(name = "phosphorus")
    val phosphorus: Double,
    @Json(name = "phosphorus_100g")
    val phosphorus100g: Double,
    @Json(name = "phosphorus_unit")
    val phosphorusUnit: String,
    @Json(name = "phosphorus_value")
    val phosphorusValue: Int,
    @Json(name = "polyols")
    val polyols: Int,
    @Json(name = "polyols_100g")
    val polyols100g: Int,
    @Json(name = "polyols_label")
    val polyolsLabel: String,
    @Json(name = "polyols_serving")
    val polyolsServing: Double,
    @Json(name = "polyols_unit")
    val polyolsUnit: String,
    @Json(name = "polyols_value")
    val polyolsValue: Int,
    @Json(name = "polyunsaturated-fat")
    val polyunsaturatedFat: Double,
    @Json(name = "polyunsaturated-fat_100g")
    val polyunsaturatedFat100g: Double,
    @Json(name = "polyunsaturated-fat_label")
    val polyunsaturatedFatLabel: String,
    @Json(name = "polyunsaturated-fat_serving")
    val polyunsaturatedFatServing: Double,
    @Json(name = "polyunsaturated-fat_unit")
    val polyunsaturatedFatUnit: String,
    @Json(name = "polyunsaturated-fat_value")
    val polyunsaturatedFatValue: Double,
    @Json(name = "proteins")
    val proteins: Double,
    @Json(name = "proteins_100g")
    val proteins100g: Double,
    @Json(name = "proteins_prepared_unit")
    val proteinsPreparedUnit: String,
    @Json(name = "proteins_serving")
    val proteinsServing: Double,
    @Json(name = "proteins_unit")
    val proteinsUnit: String,
    @Json(name = "proteins_value")
    val proteinsValue: Double,
    @Json(name = "salt")
    val salt: Double,
    @Json(name = "salt_100g")
    val salt100g: Double,
    @Json(name = "salt_prepared_unit")
    val saltPreparedUnit: String,
    @Json(name = "salt_serving")
    val saltServing: Double,
    @Json(name = "salt_unit")
    val saltUnit: String,
    @Json(name = "salt_value")
    val saltValue: Double,
    @Json(name = "saturated-fat")
    val saturatedFat: Double,
    @Json(name = "saturated-fat_100g")
    val saturatedFat100g: Double,
    @Json(name = "saturated-fat_prepared_unit")
    val saturatedFatPreparedUnit: String,
    @Json(name = "saturated-fat_serving")
    val saturatedFatServing: Double,
    @Json(name = "saturated-fat_unit")
    val saturatedFatUnit: String,
    @Json(name = "saturated-fat_value")
    val saturatedFatValue: Double,
    @Json(name = "sodium")
    val sodium: Double,
    @Json(name = "sodium_100g")
    val sodium100g: Double,
    @Json(name = "sodium_prepared_unit")
    val sodiumPreparedUnit: String,
    @Json(name = "sodium_serving")
    val sodiumServing: Double,
    @Json(name = "sodium_unit")
    val sodiumUnit: String,
    @Json(name = "sodium_value")
    val sodiumValue: Double,
    @Json(name = "sugars")
    val sugars: Double,
    @Json(name = "sugars_100g")
    val sugars100g: Double,
    @Json(name = "sugars_modifier")
    val sugarsModifier: String,
    @Json(name = "sugars_prepared_unit")
    val sugarsPreparedUnit: String,
    @Json(name = "sugars_serving")
    val sugarsServing: Double,
    @Json(name = "sugars_unit")
    val sugarsUnit: String,
    @Json(name = "sugars_value")
    val sugarsValue: Double,
    @Json(name = "trans-fat")
    val transFat: Double,
    @Json(name = "trans-fat_100g")
    val transFat100g: Double,
    @Json(name = "trans-fat_label")
    val transFatLabel: String,
    @Json(name = "trans-fat_serving")
    val transFatServing: Double,
    @Json(name = "trans-fat_unit")
    val transFatUnit: String,
    @Json(name = "trans-fat_value")
    val transFatValue: Double,
    @Json(name = "vitamin-a")
    val vitaminA: Int,
    @Json(name = "vitamin-a_100g")
    val vitaminA100g: Int,
    @Json(name = "vitamin-a_unit")
    val vitaminAUnit: String,
    @Json(name = "vitamin-a_value")
    val vitaminAValue: Int,
    @Json(name = "vitamin-b1")
    val vitaminB1: Double,
    @Json(name = "vitamin-b1_100g")
    val vitaminB1100g: Double,
    @Json(name = "vitamin-b12")
    val vitaminB12: Int,
    @Json(name = "vitamin-b12_100g")
    val vitaminB12100g: Int,
    @Json(name = "vitamin-b12_label")
    val vitaminB12Label: String,
    @Json(name = "vitamin-b12_serving")
    val vitaminB12Serving: Int,
    @Json(name = "vitamin-b12_unit")
    val vitaminB12Unit: String,
    @Json(name = "vitamin-b12_value")
    val vitaminB12Value: Int,
    @Json(name = "vitamin-b1_label")
    val vitaminB1Label: String,
    @Json(name = "vitamin-b1_serving")
    val vitaminB1Serving: Double,
    @Json(name = "vitamin-b1_unit")
    val vitaminB1Unit: String,
    @Json(name = "vitamin-b1_value")
    val vitaminB1Value: Double,
    @Json(name = "vitamin-b2")
    val vitaminB2: Double,
    @Json(name = "vitamin-b2_100g")
    val vitaminB2100g: Double,
    @Json(name = "vitamin-b2_label")
    val vitaminB2Label: String,
    @Json(name = "vitamin-b2_serving")
    val vitaminB2Serving: Double,
    @Json(name = "vitamin-b2_unit")
    val vitaminB2Unit: String,
    @Json(name = "vitamin-b2_value")
    val vitaminB2Value: Double,
    @Json(name = "vitamin-b6")
    val vitaminB6: Double,
    @Json(name = "vitamin-b6_100g")
    val vitaminB6100g: Double,
    @Json(name = "vitamin-b6_label")
    val vitaminB6Label: String,
    @Json(name = "vitamin-b6_serving")
    val vitaminB6Serving: Double,
    @Json(name = "vitamin-b6_unit")
    val vitaminB6Unit: String,
    @Json(name = "vitamin-b6_value")
    val vitaminB6Value: Double,
    @Json(name = "vitamin-b9")
    val vitaminB9: Double,
    @Json(name = "vitamin-b9_100g")
    val vitaminB9100g: Double,
    @Json(name = "vitamin-b9_label")
    val vitaminB9Label: String,
    @Json(name = "vitamin-b9_serving")
    val vitaminB9Serving: Double,
    @Json(name = "vitamin-b9_unit")
    val vitaminB9Unit: String,
    @Json(name = "vitamin-b9_value")
    val vitaminB9Value: Int,
    @Json(name = "vitamin-c")
    val vitaminC: Int,
    @Json(name = "vitamin-c_100g")
    val vitaminC100g: Int,
    @Json(name = "vitamin-c_unit")
    val vitaminCUnit: String,
    @Json(name = "vitamin-c_value")
    val vitaminCValue: Int,
    @Json(name = "vitamin-d")
    val vitaminD: Double,
    @Json(name = "vitamin-d_100g")
    val vitaminD100g: Double,
    @Json(name = "vitamin-d_label")
    val vitaminDLabel: String,
    @Json(name = "vitamin-d_serving")
    val vitaminDServing: Double,
    @Json(name = "vitamin-d_unit")
    val vitaminDUnit: String,
    @Json(name = "vitamin-d_value")
    val vitaminDValue: Double,
    @Json(name = "vitamin-e")
    val vitaminE: Double,
    @Json(name = "vitamin-e_100g")
    val vitaminE100g: Double,
    @Json(name = "vitamin-e_label")
    val vitaminELabel: String,
    @Json(name = "vitamin-e_serving")
    val vitaminEServing: Double,
    @Json(name = "vitamin-e_unit")
    val vitaminEUnit: String,
    @Json(name = "vitamin-e_value")
    val vitaminEValue: Double,
    @Json(name = "vitamin-pp")
    val vitaminPp: Double,
    @Json(name = "vitamin-pp_100g")
    val vitaminPp100g: Double,
    @Json(name = "vitamin-pp_label")
    val vitaminPpLabel: String,
    @Json(name = "vitamin-pp_serving")
    val vitaminPpServing: Double,
    @Json(name = "vitamin-pp_unit")
    val vitaminPpUnit: String,
    @Json(name = "vitamin-pp_value")
    val vitaminPpValue: Int
)